class MenuAuthDetail {
  static String? ScoreCard;
  static String? Earnings;
  static String? Performance;
  static String? Target;
  static String? Challenges;
  static String? Stocks;
  static String? PriceList;
  static String? OfferZone;
  static String? Enquiries;
  static String? Walkins;
  static String? Leads;
  static String? Orders;
  static String? Followup;
  static String? Accounts;
  static String? Profile;
  static String? Dashboard;
  static String? KPI;
  static String? Feeds;
  static String? NewFeeds;
  static String? Analytics;
}