name: sellerkit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2

environment:
  sdk: ">=2.16.1 <3.0.0"
  

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_staggered_animations: ^1.0.0
  introduction_screen: ^3.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.6
  simple_animations: ^5.0.0+2
  http: ^0.13.5
  get: ^4.6.5
  pin_code_fields: ^7.3.0
  pie_chart: ^5.3.2
  share: ^2.0.4
  platform_device_id: ^1.0.1
  expandable_text: ^2.3.0
  flutter_switch: ^0.3.2
  lottie: ^1.4.1
  sqflite: ^2.2.2
  path: ^1.8.0
  file_picker: ^5.2.2
  permission_handler: ^10.0.0
  jiffy: ^5.0.0
  url_launcher: ^6.1.5
  local_auth: ^2.1.2
  timeline_tile: ^2.0.0
  receive_sharing_intent: ^1.4.5
  webview_flutter: ^3.0.4
  swipe_image_gallery: ^0.8.0
  any_link_preview: ^2.0.9
  flutter_widget_from_html: ^0.9.0
  toggle_switch: ^2.0.1
  path_provider: ^2.0.11
  image_picker: ^0.8.3+1 
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^14.1.2
  firebase_core: ^2.3.0
  fluttertoast: ^8.0.9
  camera: ^0.10.3+2
  video_player: ^2.6.0
  easy_pdf_viewer: ^1.0.6
  screen_capture_event: ^1.1.1
  mobile_scanner: ^3.2.0
  geolocator: ^9.0.2
  pdf: ^3.8.1
  printing: ^5.9.3
  google_maps_flutter: ^2.2.1
  #screenshot: ^1.3.0



dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "Assets/SellerSymbol.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SEGOEUIL
      fonts:
        - asset: Assets/SEGOEUIL.ttf
    - family: HelveticaNow
      fonts:
        - asset: Assets/HelveticaNow.ttf
    - family: ayar
      fonts:
        - asset: Assets/ayar.ttf
    - family: Celias-Medium
      fonts:
        - asset: Assets/Celias-Medium.ttf
    - family: Ordina-WideThin
      fonts:
        - asset: Assets/Ordina-WideThin.ttf
    - family: TruenoRound
      fonts:
        - asset: Assets/TruenoRound.otf
    - family: Quicksand_Light
      fonts:
        - asset: Assets/Quicksand/Quicksand_Light.otf
    - family: NovaRegular
      fonts:
        - asset: Assets/nova/NovaRegular.otf
    - family: OpenSans-Regular
      fonts:
        - asset: Assets/OpenSans/OpenSans-Regular.ttf
    - family: Sabon
      fonts:
        - asset: Assets/Sabon/Sabon.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
